package db;
// Generated Feb 19, 2018 3:42:49 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TbBasicInfo generated by hbm2java
 */
@Entity
@Table(name="tb_basic_info"
    ,catalog="db_epacs_n31589a3a33c5dca256m8650910ed"
)
public class TbBasicInfo  implements java.io.Serializable {


     private Integer biId;
     private TbUserAccount tbUserAccount;
     private String biFirstName;
     private String biLastName;
     private String biJapanName;
     private String biStatus;

    public TbBasicInfo() {
    }

	
    public TbBasicInfo(TbUserAccount tbUserAccount) {
        this.tbUserAccount = tbUserAccount;
    }
    public TbBasicInfo(TbUserAccount tbUserAccount, String biFirstName, String biLastName, String biJapanName, String biStatus) {
       this.tbUserAccount = tbUserAccount;
       this.biFirstName = biFirstName;
       this.biLastName = biLastName;
       this.biJapanName = biJapanName;
       this.biStatus = biStatus;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="bi_id", unique=true, nullable=false)
    public Integer getBiId() {
        return this.biId;
    }
    
    public void setBiId(Integer biId) {
        this.biId = biId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tb_user_account_ua_id", nullable=false)
    public TbUserAccount getTbUserAccount() {
        return this.tbUserAccount;
    }
    
    public void setTbUserAccount(TbUserAccount tbUserAccount) {
        this.tbUserAccount = tbUserAccount;
    }

    
    @Column(name="bi_first_name", length=100)
    public String getBiFirstName() {
        return this.biFirstName;
    }
    
    public void setBiFirstName(String biFirstName) {
        this.biFirstName = biFirstName;
    }

    
    @Column(name="bi_last_name", length=100)
    public String getBiLastName() {
        return this.biLastName;
    }
    
    public void setBiLastName(String biLastName) {
        this.biLastName = biLastName;
    }

    
    @Column(name="bi_japan_name")
    public String getBiJapanName() {
        return this.biJapanName;
    }
    
    public void setBiJapanName(String biJapanName) {
        this.biJapanName = biJapanName;
    }

    
    @Column(name="bi_status", length=45)
    public String getBiStatus() {
        return this.biStatus;
    }
    
    public void setBiStatus(String biStatus) {
        this.biStatus = biStatus;
    }




}


