package db;
// Generated Feb 19, 2018 3:42:49 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbCatagoryInfo generated by hbm2java
 */
@Entity
@Table(name="tb_catagory_info"
    ,catalog="db_epacs_n31589a3a33c5dca256m8650910ed"
)
public class TbCatagoryInfo  implements java.io.Serializable {


     private Integer ciId;
     private String ciTitle;
     private String ciStatus;
     private Set<TbSubcatagoryInfo> tbSubcatagoryInfos = new HashSet<TbSubcatagoryInfo>(0);

    public TbCatagoryInfo() {
    }

    public TbCatagoryInfo(String ciTitle, String ciStatus, Set<TbSubcatagoryInfo> tbSubcatagoryInfos) {
       this.ciTitle = ciTitle;
       this.ciStatus = ciStatus;
       this.tbSubcatagoryInfos = tbSubcatagoryInfos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ci_id", unique=true, nullable=false)
    public Integer getCiId() {
        return this.ciId;
    }
    
    public void setCiId(Integer ciId) {
        this.ciId = ciId;
    }

    
    @Column(name="ci_title", length=100)
    public String getCiTitle() {
        return this.ciTitle;
    }
    
    public void setCiTitle(String ciTitle) {
        this.ciTitle = ciTitle;
    }

    
    @Column(name="ci_status", length=45)
    public String getCiStatus() {
        return this.ciStatus;
    }
    
    public void setCiStatus(String ciStatus) {
        this.ciStatus = ciStatus;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbCatagoryInfo")
    public Set<TbSubcatagoryInfo> getTbSubcatagoryInfos() {
        return this.tbSubcatagoryInfos;
    }
    
    public void setTbSubcatagoryInfos(Set<TbSubcatagoryInfo> tbSubcatagoryInfos) {
        this.tbSubcatagoryInfos = tbSubcatagoryInfos;
    }




}


