package db;
// Generated Feb 19, 2018 3:42:49 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TbImagesInfo generated by hbm2java
 */
@Entity
@Table(name="tb_images_info"
    ,catalog="db_epacs_n31589a3a33c5dca256m8650910ed"
)
public class TbImagesInfo  implements java.io.Serializable {


     private Integer iiId;
     private TbProductInfo tbProductInfo;
     private String iiPath;
     private String iiStatus;

    public TbImagesInfo() {
    }

	
    public TbImagesInfo(TbProductInfo tbProductInfo) {
        this.tbProductInfo = tbProductInfo;
    }
    public TbImagesInfo(TbProductInfo tbProductInfo, String iiPath, String iiStatus) {
       this.tbProductInfo = tbProductInfo;
       this.iiPath = iiPath;
       this.iiStatus = iiStatus;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ii_id", unique=true, nullable=false)
    public Integer getIiId() {
        return this.iiId;
    }
    
    public void setIiId(Integer iiId) {
        this.iiId = iiId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tb_product_info_pi_id", nullable=false)
    public TbProductInfo getTbProductInfo() {
        return this.tbProductInfo;
    }
    
    public void setTbProductInfo(TbProductInfo tbProductInfo) {
        this.tbProductInfo = tbProductInfo;
    }

    
    @Column(name="ii_path")
    public String getIiPath() {
        return this.iiPath;
    }
    
    public void setIiPath(String iiPath) {
        this.iiPath = iiPath;
    }

    
    @Column(name="ii_status", length=45)
    public String getIiStatus() {
        return this.iiStatus;
    }
    
    public void setIiStatus(String iiStatus) {
        this.iiStatus = iiStatus;
    }




}


