package db;
// Generated Feb 19, 2018 3:42:49 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbPageAuthentication generated by hbm2java
 */
@Entity
@Table(name="tb_page_authentication"
    ,catalog="db_epacs_n31589a3a33c5dca256m8650910ed"
)
public class TbPageAuthentication  implements java.io.Serializable {


     private Integer paId;
     private String paPageTitle;
     private String paStatus;
     private Set<TbUserRoleHasTbPageAuthentication> tbUserRoleHasTbPageAuthentications = new HashSet<TbUserRoleHasTbPageAuthentication>(0);

    public TbPageAuthentication() {
    }

    public TbPageAuthentication(String paPageTitle, String paStatus, Set<TbUserRoleHasTbPageAuthentication> tbUserRoleHasTbPageAuthentications) {
       this.paPageTitle = paPageTitle;
       this.paStatus = paStatus;
       this.tbUserRoleHasTbPageAuthentications = tbUserRoleHasTbPageAuthentications;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="pa_id", unique=true, nullable=false)
    public Integer getPaId() {
        return this.paId;
    }
    
    public void setPaId(Integer paId) {
        this.paId = paId;
    }

    
    @Column(name="pa_page_title", length=100)
    public String getPaPageTitle() {
        return this.paPageTitle;
    }
    
    public void setPaPageTitle(String paPageTitle) {
        this.paPageTitle = paPageTitle;
    }

    
    @Column(name="pa_status", length=45)
    public String getPaStatus() {
        return this.paStatus;
    }
    
    public void setPaStatus(String paStatus) {
        this.paStatus = paStatus;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbPageAuthentication")
    public Set<TbUserRoleHasTbPageAuthentication> getTbUserRoleHasTbPageAuthentications() {
        return this.tbUserRoleHasTbPageAuthentications;
    }
    
    public void setTbUserRoleHasTbPageAuthentications(Set<TbUserRoleHasTbPageAuthentication> tbUserRoleHasTbPageAuthentications) {
        this.tbUserRoleHasTbPageAuthentications = tbUserRoleHasTbPageAuthentications;
    }




}


