package db;
// Generated Feb 19, 2018 3:42:49 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbSubcatagoryInfo generated by hbm2java
 */
@Entity
@Table(name="tb_subcatagory_info"
    ,catalog="db_epacs_n31589a3a33c5dca256m8650910ed"
)
public class TbSubcatagoryInfo  implements java.io.Serializable {


     private Integer siId;
     private TbCatagoryInfo tbCatagoryInfo;
     private String siTitle;
     private String siStatus;
     private Set<TbProductInfo> tbProductInfos = new HashSet<TbProductInfo>(0);

    public TbSubcatagoryInfo() {
    }

	
    public TbSubcatagoryInfo(TbCatagoryInfo tbCatagoryInfo) {
        this.tbCatagoryInfo = tbCatagoryInfo;
    }
    public TbSubcatagoryInfo(TbCatagoryInfo tbCatagoryInfo, String siTitle, String siStatus, Set<TbProductInfo> tbProductInfos) {
       this.tbCatagoryInfo = tbCatagoryInfo;
       this.siTitle = siTitle;
       this.siStatus = siStatus;
       this.tbProductInfos = tbProductInfos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="si_id", unique=true, nullable=false)
    public Integer getSiId() {
        return this.siId;
    }
    
    public void setSiId(Integer siId) {
        this.siId = siId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tb_catagory_info_ci_id", nullable=false)
    public TbCatagoryInfo getTbCatagoryInfo() {
        return this.tbCatagoryInfo;
    }
    
    public void setTbCatagoryInfo(TbCatagoryInfo tbCatagoryInfo) {
        this.tbCatagoryInfo = tbCatagoryInfo;
    }

    
    @Column(name="si_title", length=100)
    public String getSiTitle() {
        return this.siTitle;
    }
    
    public void setSiTitle(String siTitle) {
        this.siTitle = siTitle;
    }

    
    @Column(name="si_status", length=45)
    public String getSiStatus() {
        return this.siStatus;
    }
    
    public void setSiStatus(String siStatus) {
        this.siStatus = siStatus;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbSubcatagoryInfo")
    public Set<TbProductInfo> getTbProductInfos() {
        return this.tbProductInfos;
    }
    
    public void setTbProductInfos(Set<TbProductInfo> tbProductInfos) {
        this.tbProductInfos = tbProductInfos;
    }




}


