package db;
// Generated Feb 19, 2018 3:42:49 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TbUserAccountHasTbUserRole generated by hbm2java
 */
@Entity
@Table(name="tb_user_account_has_tb_user_role"
    ,catalog="db_epacs_n31589a3a33c5dca256m8650910ed"
)
public class TbUserAccountHasTbUserRole  implements java.io.Serializable {


     private Integer uaurId;
     private TbUserAccount tbUserAccount;
     private TbUserRole tbUserRole;
     private String uaurStatus;

    public TbUserAccountHasTbUserRole() {
    }

	
    public TbUserAccountHasTbUserRole(TbUserAccount tbUserAccount, TbUserRole tbUserRole) {
        this.tbUserAccount = tbUserAccount;
        this.tbUserRole = tbUserRole;
    }
    public TbUserAccountHasTbUserRole(TbUserAccount tbUserAccount, TbUserRole tbUserRole, String uaurStatus) {
       this.tbUserAccount = tbUserAccount;
       this.tbUserRole = tbUserRole;
       this.uaurStatus = uaurStatus;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="uaur_id", unique=true, nullable=false)
    public Integer getUaurId() {
        return this.uaurId;
    }
    
    public void setUaurId(Integer uaurId) {
        this.uaurId = uaurId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tb_user_account_ua_id", nullable=false)
    public TbUserAccount getTbUserAccount() {
        return this.tbUserAccount;
    }
    
    public void setTbUserAccount(TbUserAccount tbUserAccount) {
        this.tbUserAccount = tbUserAccount;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tb_user_role_ur_id", nullable=false)
    public TbUserRole getTbUserRole() {
        return this.tbUserRole;
    }
    
    public void setTbUserRole(TbUserRole tbUserRole) {
        this.tbUserRole = tbUserRole;
    }

    
    @Column(name="uaur_status", length=45)
    public String getUaurStatus() {
        return this.uaurStatus;
    }
    
    public void setUaurStatus(String uaurStatus) {
        this.uaurStatus = uaurStatus;
    }




}


