package db;
// Generated Feb 19, 2018 3:42:49 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TbUserLog generated by hbm2java
 */
@Entity
@Table(name="tb_user_log"
    ,catalog="db_epacs_n31589a3a33c5dca256m8650910ed"
)
public class TbUserLog  implements java.io.Serializable {


     private Integer ulId;
     private TbUserAccount tbUserAccount;
     private String ulTime;
     private String ulIpAddress;
     private String ulStatus;
     private String ulDiscription;

    public TbUserLog() {
    }

	
    public TbUserLog(TbUserAccount tbUserAccount) {
        this.tbUserAccount = tbUserAccount;
    }
    public TbUserLog(TbUserAccount tbUserAccount, String ulTime, String ulIpAddress, String ulStatus, String ulDiscription) {
       this.tbUserAccount = tbUserAccount;
       this.ulTime = ulTime;
       this.ulIpAddress = ulIpAddress;
       this.ulStatus = ulStatus;
       this.ulDiscription = ulDiscription;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ul_id", unique=true, nullable=false)
    public Integer getUlId() {
        return this.ulId;
    }
    
    public void setUlId(Integer ulId) {
        this.ulId = ulId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tb_user_account_ua_id", nullable=false)
    public TbUserAccount getTbUserAccount() {
        return this.tbUserAccount;
    }
    
    public void setTbUserAccount(TbUserAccount tbUserAccount) {
        this.tbUserAccount = tbUserAccount;
    }

    
    @Column(name="ul_time", length=45)
    public String getUlTime() {
        return this.ulTime;
    }
    
    public void setUlTime(String ulTime) {
        this.ulTime = ulTime;
    }

    
    @Column(name="ul_ip_address", length=45)
    public String getUlIpAddress() {
        return this.ulIpAddress;
    }
    
    public void setUlIpAddress(String ulIpAddress) {
        this.ulIpAddress = ulIpAddress;
    }

    
    @Column(name="ul_status", length=45)
    public String getUlStatus() {
        return this.ulStatus;
    }
    
    public void setUlStatus(String ulStatus) {
        this.ulStatus = ulStatus;
    }

    
    @Column(name="ul_discription")
    public String getUlDiscription() {
        return this.ulDiscription;
    }
    
    public void setUlDiscription(String ulDiscription) {
        this.ulDiscription = ulDiscription;
    }




}


